### ISSUE TITLE
Using Pool<T> with BTreeMap in Rust

### ISSUE THREAD

**Issue by sicarius01** [fereidani/opool#3]
Hello,

I am trying to use opool to create a memory pool for T and use it as values in a BTreeMap which is a member of a struct. I am facing lifetime issues that I can't seem to resolve. Could you provide any examples or concepts on how this can be achieved?

Thank you!

**Comment by fereidani** [comment]
Create your pool on a global level and use it there. There are examples in here, lifetime for your objects will be static and they will be garbage collected as soon as you drop your main struct: https://github.com/fereidani/opool/blob/main/benches/bench.rs
